name: Check proposed branch

on:
  workflow_dispatch:
  push:
    branches:
      - "*-proposed-*"

jobs:
  check_packages:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          # Intel based
          - macos-13
          # ARM based
          - macos-14
          - windows-2019

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: |
          uv python install

      - name: Check Packages
        run: |
          git fetch
          uv run ci/check_packages.py --report check-${{ matrix.os }}.json
        env:
          PYTHONUNBUFFERED: 1
          CLYDE_GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}

      - name: Upload check report
        uses: actions/upload-artifact@v4
        with:
          name: check-${{ matrix.os }}.json
          path: check-*.json

  merge_valid_changes:
    runs-on: ubuntu-22.04
    needs:
      - check_packages

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to ensure `base_branch` is available in ci/fetch even if the
          # job is not started from it
          fetch-depth: 0

      - name: Download check reports
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: check-*.json
          merge-multiple: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: |
          uv python install

      - name: Merge valid changes
        run: |
          uv run ci/merge_valid_changes.py check-*.json
