name: fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  fetch:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to ensure `base_branch` is available in ci/fetch even if the
          # job is not started from it
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: |
          uv python install

      - name: Fetch
        run: |
          git config user.name "ClydeStore bot"
          git config user.email "clydestore@agateau.com"
          uv run ci/fetch.py
          uv run ci/open_prs.py
        env:
          PYTHONUNBUFFERED: 1
          # PR_GITHUB_TOKEN must be a PAT able to open PR, see
          # https://github.com/peter-evans/create-pull-request/issues/48
          CLYDE_GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
