name: Fetch

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          # Needed to ensure `base_branch` is available in ci/fetch even if the
          # job is not started from it
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Fetch
        run: |
          git config user.name "ClydeStore bot"
          git config user.email "clydestore@agateau.com"
          ci/fetch *.yaml */index.yaml
        env:
          PYTHONUNBUFFERED: 1
          CLYDE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
