name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  fetch:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to ensure `base_branch` is available in ci/fetch even if the
          # job is not started from it
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: |
          cd ci
          uv python install

      - name: Fetch
        run: |
          cd ci
          uv run fetch.py *.yaml */index.yaml
        env:
          PYTHONUNBUFFERED: 1
          CLYDE_GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
