name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all
