name: Main

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-packages:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Check Packages
        run: ci/check-packages
