name: Main

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-packages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Check Packages
        run: ci/check-packages
